// Animation names
#define SCORPSOLDIER_ANIM_IDLE 0
#define SCORPSOLDIER_ANIM_RUN 1
#define SCORPSOLDIER_ANIM_WALK 2
#define SCORPSOLDIER_ANIM_FIRE 3
#define SCORPSOLDIER_ANIM_MELEE 4
#define SCORPSOLDIER_ANIM_WOUND 5
#define SCORPSOLDIER_ANIM_SIGHT 6
#define SCORPSOLDIER_ANIM_DEATH 7

// Color names

// Patch names

// Names of collision boxes
#define SCORPSOLDIER_COLLISION_BOX_PART_NAME 0
#define SCORPSOLDIER_COLLISION_BOX_DEATH 1

// Attaching position names
#define SCORPSOLDIER_ATTACHMENT_GUN 0
#define SCORPSOLDIER_ATTACHMENT_FLARE 1

// Sound names
