// Animation names
#define MAMUTMAN_ANIM_DEFAULT 0
#define MAMUTMAN_ANIM_IDLE 1
#define MAMUTMAN_ANIM_WALK 2
#define MAMUTMAN_ANIM_RUN 3
#define MAMUTMAN_ANIM_FIRE 4
#define MAMUTMAN_ANIM_MELEE 5
#define MAMUTMAN_ANIM_TELEPORT 6
#define MAMUTMAN_ANIM_WOUND01 7
#define MAMUTMAN_ANIM_WOUND02 8
#define MAMUTMAN_ANIM_WOUND03 9
#define MAMUTMAN_ANIM_DEATH01 10
#define MAMUTMAN_ANIM_DEATH02 11

// Color names

// Patch names

// Names of collision boxes
#define MAMUTMAN_COLLISION_BOX_DEFAULT 0
#define MAMUTMAN_COLLISION_BOX_DEATH 1

// Attaching position names
#define MAMUTMAN_ATTACHMENT_GUN 0

// Sound names
