// Animation names
#define SLEDGEHAMMER_ANIM_DEFAULT_ANIMATION 0
#define SLEDGEHAMMER_ANIM_PULL 1
#define SLEDGEHAMMER_ANIM_PULLOUT 2
#define SLEDGEHAMMER_ANIM_WAIT1 3
#define SLEDGEHAMMER_ANIM_WAIT2 4
#define SLEDGEHAMMER_ANIM_WAIT3 5
#define SLEDGEHAMMER_ANIM_ATTACK01 6
#define SLEDGEHAMMER_ANIM_ATTACK02 7

// Color names

// Patch names

// Names of collision boxes
#define SLEDGEHAMMER_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define SLEDGEHAMMER_ATTACHMENT_HAMMERITEM 0

// Sound names
