// Animation names
#define SPIDERSMALL_ANIM_DEFAULT 0
#define SPIDERSMALL_ANIM_HATCHPOSE 1
#define SPIDERSMALL_ANIM_HATCH 2
#define SPIDERSMALL_ANIM_HANGING 3
#define SPIDERSMALL_ANIM_CLIMBDOWN 4
#define SPIDERSMALL_ANIM_UNDERGROUND 5
#define SPIDERSMALL_ANIM_DIGOUT 6
#define SPIDERSMALL_ANIM_IDLE 7
#define SPIDERSMALL_ANIM_WALK 8
#define SPIDERSMALL_ANIM_FIRE 9
#define SPIDERSMALL_ANIM_MELEE 10
#define SPIDERSMALL_ANIM_WOUND 11
#define SPIDERSMALL_ANIM_DEATH 12

// Color names

// Patch names

// Names of collision boxes
#define SPIDERSMALL_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define SPIDERSMALL_ATTACHMENT_ELECTRICITY 0

// Sound names
