// Animation names
#define ZORGPRO_ANIM_DEFAULT 0
#define ZORGPRO_ANIM_IDLE 1
#define ZORGPRO_ANIM_IDLE_HEAVY 2
#define ZORGPRO_ANIM_IDLEFIGHT 3
#define ZORGPRO_ANIM_IDLEFIGHT_HEAVY 4
#define ZORGPRO_ANIM_IDLEPOSE 5
#define ZORGPRO_ANIM_WALK 6
#define ZORGPRO_ANIM_WALK_HEAVY 7
#define ZORGPRO_ANIM_RUN 8
#define ZORGPRO_ANIM_FIRE 9
#define ZORGPRO_ANIM_FIRE_HEAVY 10
#define ZORGPRO_ANIM_THROW 11
#define ZORGPRO_ANIM_MELEE 12
#define ZORGPRO_ANIM_MELEE_HEAVY 13
#define ZORGPRO_ANIM_WOUND 14
#define ZORGPRO_ANIM_WOUND_HEAVY 15
#define ZORGPRO_ANIM_DEATHBACK 16
#define ZORGPRO_ANIM_DEATHFORW 17
#define ZORGPRO_ANIM_UNARMEDWALK 18
#define ZORGPRO_ANIM_UNARMEDIDLE 19
#define ZORGPRO_ANIM_UNARMEDSIT 20

// Color names

// Patch names

// Names of collision boxes
#define ZORGPRO_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define ZORGPRO_ATTACHMENT_GUN_COMMANDER 0
#define ZORGPRO_ATTACHMENT_GUN_SOLDIER 1
#define ZORGPRO_ATTACHMENT_GUN_SNIPER 2
#define ZORGPRO_ATTACHMENT_BLADE 3
#define ZORGPRO_ATTACHMENT_BARREL4 4
#define ZORGPRO_ATTACHMENT_GUNBODY 5
#define ZORGPRO_ATTACHMENT_BARREL1 6
#define ZORGPRO_ATTACHMENT_BARREL2 7
#define ZORGPRO_ATTACHMENT_BARREL3 8

// Sound names
